[project]
channels = ["conda-forge", "bioconda"]
name = "Z-DoTT"
platforms = ["linux-64"]

[environments]
default = ["python", "R"]
liftoff = ["liftoff"]
rust = ["rust"]
nextflow = ["nextflow"]

####################################################################################################
# liftoff: lifting the GENCODE GRCh38 annotation to the CHM13v2 assembly
####################################################################################################
[feature.liftoff.dependencies]
liftoff = "==1.6.3"
samtools = "==1.21"

[feature.liftoff.tasks."setup/liftoff"]
cmd = "./liftoff-CHM13v2-annotation.sh $GENCODE_VERSION $ASSEMBLIES"
env = { GENCODE_VERSION = "47", ASSEMBLIES = "$PIXI_PROJECT_ROOT/assemblies" }
cwd = "setup/annotation"

####################################################################################################
# Nextflow: data preprocessing
####################################################################################################
[feature.nextflow.dependencies]
nextflow = "==24.10.0"
samtools = "==1.21"
tabix = "==1.11"
star = "==2.7.10a"
salmon = "==1.10.3"
gffread = "==0.12.7"

[feature.nextflow.tasks."setup/download-annotations"]
cmd = "bash download-annotations.sh $HUMAN_VERSION $MOUSE_VERSION $ASSEMBLIES"
env = { HUMAN_VERSION = "47", MOUSE_VERSION = "M36", ASSEMBLIES = "$PIXI_PROJECT_ROOT/assemblies" }
cwd = "setup/annotation"

[feature.nextflow.tasks."setup/make-nfcore-indexes"]
cmd = [
    "./index.sh",
    "$PIXI_PROJECT_ROOT/assemblies", # Assemblies directory
    "$PIXI_PROJECT_ROOT/setup/pre-mapping/results", # Pre-mapping results directory
    "$PIXI_PROJECT_ROOT/analyses/nfcore/resources/indexes"  # Indexes output directory
]
cwd = "setup/nfcore"

[feature.nextflow.tasks."nfcore/rnaseq"]
cmd = [
    "cd", "$PIXI_PROJECT_ROOT/analyses/nfcore/rnaseq/{{ directory }}", "&&",
    "nfcore", "run", "-c", "resources/nfcore.config", "-params-file", "resources/params.yaml", "-resume",
    "-profile", "slurm,latency", "-r", "bc8cab3184011fd6903afddf0da731681eb3a942", "alnfedorov/rnaseq"
]
args = ["directory"]

[feature.nextflow.tasks."nfcore/fetchngs"]
cmd = [
    # Change to the directory with id.csv
    "cd", "$PIXI_PROJECT_ROOT/data/{{ directory }}/fastq", "&&",
    # Run nfcore/fetchngs
    "nextflow", "run", "-resume", "-profile", "singularity",
    "-r", "7544cb9297a0db754120bd1cb8d7df4586a60610", "nf-core/fetchngs",
    "--input", "id.csv", "--outdir", "results", "&&",
    # Save FASTQ files and discard Nextflow files
    "mv", "results/fastq/*.gz", ".", "&&",
    "mv", "results/samplesheet/samplesheet.csv", ".", "&&",
    "cat", "results/fastq/md5/*.md5", ">", "MD5.txt", ";", # Using ';' to avoid error if no md5 files are present (e.g. for SRA downloads)
    "rm", "-rf", ".nextflow", ".nextflow.log", "work", "results"
]
args = ["directory"]

########################################################################################################################
# Rust: for building the latest version of REAT
########################################################################################################################
[feature.rust.dependencies]
rust = "==1.84.0"
cmake = "==4.0.2"
gcc = "==12.4"

[feature.rust.tasks."setup/REAT"]
cmd = [
    "mkdir", "-p", "cargo", "&&",
    "cargo", "install", "-v", "--git", "https://github.com/alnfedorov/reat",
    "--rev", "c166a6c740739c6dbab7bdab971a912bea1031c5", "--locked",
    "--root", "cargo",
    "--force", "&&",
    "mv", "cargo/bin/reat", "reat", "&&",
    "rm", "-rf", "cargo"
]
cwd = "analyses/A2I/resources"

####################################################################################################
# Python: bioinformatics stories
####################################################################################################
[feature.python.dependencies]
python = "==3.12.8"
pixi-pycharm = "*"
tabix = "==1.11"
bedtools = "==2.31.1"

# Python dependecies must be managed only using pip to allow rebuilding wheels when needed
[feature.python.pypi-dependencies]
attrs = "==23.2.0"
biobit = "==0.0.4"
biopython = "==1.84"
intervaltree = "==3.1.0"
ipython = "==8.25.0"
joblib = "==1.4.0"
matplotlib = "==3.9.2"
matplotlib-venn = "==1.1.1"
pandas = "==2.2.1"
pybedtools = "==0.10.0"
pybigwig = "==0.3.22"
pysam = "==0.22.1"
rustworkx = "==0.15.1"
scikit-learn = "==1.5.1"
seaborn = "==0.13.2"
statsmodels = "==0.14.4"
tqdm = "==4.66.2"
viennarna = "==2.7.0"
zhuntrs = "==0.0.4"

[feature.python.activation]
env = { PYTHONPATH = "$PIXI_PROJECT_ROOT" }

[feature.python.tasks.run-py]
cmd = "python {{ script }} {{ args }}"
args = ["script", { arg = "args", default = "" }]

# Setup
[feature.python.tasks]
"setup/index-annotations" = { depends-on = [
    { task = "run-py", args = ["setup/annotation/index-liftoff-gff.py"] },
    { task = "run-py", args = ["setup/annotation/index-refseq-gff.py"] },
    { task = "run-py", args = ["setup/annotation/index-gencode-gff.py"] }
] }
"setup/derive-premap-library" = { depends-on = [
    { task = "run-py", args = ["setup/pre-mapping/derive-premap-library.py"] }
] }

## Stories
#"stories/annotation" = { depends-on = [
#    { task = "run-py", args = ["stories/annotation/filter-gencode.py"] },
#    { task = "run-py", args = ["stories/annotation/index-rna-boundaries.py"] },
#    { task = "run-py", args = ["stories/annotation/derive-rna-cores.py"] },
#    { task = "run-py", args = ["stories/annotation/resolve-gencode.py"] }
#] }
#"stories/normalization" = { depends-on = [
#    { task = "run-py", args = ["stories/normalization/bin-genomes.py"] },
#    { task = "run-py", args = ["stories/normalization/count-reads.py"] },
#    { task = "run-py", args = ["stories/normalization/vRNA-load.py"] }
#] }
#"stories/qc" = { depends-on = [
#    { task = "run-py", args = ["stories/qc/count-reads.py"] },
#    { task = "run-py", args = ["stories/qc/plot-biotypes.py"] },
#    { task = "run-py", args = ["stories/qc/plot-pca.py"] },
#    { task = "run-py", args = ["stories/qc/mapping-stats.py"] }
#] }
#"stories/A2I" = { depends-on = [
#    { task = "run-py", args = ["stories/A2I/build-viral-contigs-list.py"] },
#    { task = "run-py", args = ["stories/A2I/find-candidate-sites.py"] },
#    { task = "run-py", args = ["stories/A2I/build-editome.py"] },
#    { task = "run-py", args = ["stories/A2I/annotate-editome-sties.py"] },
#    { task = "run-py", args = ["stories/A2I/build-summary.py"] }
#] }
#
## MDA5 ligands
#[feature.python.tasks."stories/MDA5/pcalling"]
#cmd = [
#    "python", "make-config.py", "&&",
#    "python", "make-rna-models.py", "&&",
#    "python", "call-peaks.py"
#]
#cwd = "stories/MDA5/pcalling"
#
#[feature.python.tasks."stories/MDA5/clustering"]
#cmd = [
#    "python", "make-config.py", "&&",
#    "python", "derive-insulators.py", "&&",
#    "python", "peaks-prefiltering.py", "&&",
#    "python", "dsRNA-prediction.py", "&&",
#    "python", "-Xgil=0", "dsRNA-filtering.py", "&&",
#    "python", "peaks-filtering.py", "&&",
#    "python", "clustering.py"
#]
#cwd = "stories/MDA5/clustering"
#
#[feature.python.tasks."stories/MDA5/annotation"]
#cmd = [
#    "python", "make-config.py", "&&",
#    "python", "-Xgil=0", "cache-signal.py", "&&",
#    "python", "cache-counts.py", "&&",
#    "python", "cache-structures.py", "&&",
#    # Annotate all peaks/dsRNAs
#    "python", "qPCR-probes.py", "&&",
#    "python", "localization.py", "&&",
#    "python", "sequence-composition.py", "&&",
#    "python", "dsRNA-structure.py", "&&",
#    "python", "A2I-editing-index.py", "&&",
#    "python", "experimental-signal.py", "&&",
#    "python", "stat-comparisons.py", "&&",
#    # Make final summaries
#    "python", "make-summaries.py"
#]
#cwd = "stories/MDA5/annotation"
#
## Aberrantome
#[feature.python.tasks."stories/aberrantome/calculate"]
#cmd = [
#    "python", "make-config.py", "&&",
#    "python", "prepare-rnas.py", "&&",
#    "python", "count-reads.py", "&&",
#    "python", "run-dexseq.py", "&&",
#    "python", "annotate-results.py"
#]
#cwd = "stories/aberrantome/calculate"
#
#[feature.python.tasks."stories/aberrantome/plot"]
#cmd = [
#    "python", "resolve.py", "&&",
#    "python", "scores-regplot.py", "&&",
#    "python", "scores-barplot.py", "&&",
#    "python", "summary.py", "&&",
#    "python", "volcano-plot.py"
#]
#cwd = "stories/aberrantome/plot"

####################################################################################################
# R: differential expression analysis
####################################################################################################
[feature.R.dependencies]
r-base = "==4.4.2"
bioconductor-deseq2 = "==1.46.0"
bioconductor-dexseq = "==1.52.0"
bioconductor-apeglm = "==1.28.0"
